appName : Pet Store
elementsPerPage: 10
theme : org.wso2.uuf.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Pets :
      See all our amazing pets : {link: "pets"}
      Add a new pets : {link: "pets/new", icon: "fw fw-add"}
      Pet of the month : {link: "pets/snowball" }
errorPages:
  "404": /base/error/404
  default: /base/error/default