appName : BPMN Explorer
elementsPerPage: 10
lifecycle:
    - state: adopted
      show: false
    - state: new
      show: true
theme : org.wso2.uuf.theme.blue
menu :
  main :
    HOME: { icon: "fw-home", link: "#home", text: "Home" }
    MY TASKS : { icon: "fw fw-list", link: "bpmn", text: "MY TASKS" }
    CLAIMABLE TASKS : { icon: "fw fw-add", link: "bpmn/claimableTasks", text: "CLAIMABLE TASKS" }
    COMPLETED TASKS : { icon: "fw fw-bug", link: "bpmn/historicTasks", text: "COMPLETED TASKS" }
    PROCESSES : { icon: "fw fw-list", link: "bpmn/process", text: "PROCESSES" }
bpsHost: localhost
bpsPort: 9443

